### ISSUE TITLE
Getting Blank Screen

### ISSUE THREAD

**Issue by Athul-CA** [techx/quill#126]
I'm getting a blank login screen when I try to deploy this locally. I'm running on ubuntu 18.04 
These are the outputs I'm getting
![Screenshot_20190406_125459](https://user-images.githubusercontent.com/40897573/55666343-31195700-586b-11e9-9fbf-aa41b96aeb05.png)
![Screenshot_20190406_125510](https://user-images.githubusercontent.com/40897573/55666345-370f3800-586b-11e9-9177-ab0bab0407e5.png)

**Comment by Athul-CA** [comment]
I just get blank pages when i route to login or admin or any

**Comment by Athul-CA** [comment]
Resolved

**Comment by senyig20** [comment]
Can you share how did you fixed this?

**Comment by Athul-CA** [comment]
First I tried with `npm run ` then I got the blank screen.
But as I used `gulp server` it worked.
-------- Original Message --------
