### ISSUE TITLE
Autocomplete / dropdown school name

### ISSUE THREAD

**Issue by jlin816** [techx/quill#16]
Forcing standard school names would make it easier for organizers to search for schools. Semantic-UI has the perfect [autocomplete dropdown](https://semantic-ui.com/modules/dropdown.html#search-selection) module for this, so this should be a relatively simple change.

**Comment by jlin816** [comment]
@xTEddie has a list of US/Canadian schools, so check with him if you're interested in working on this.

**Comment by ehzhang** [comment]
This has actually been something that I had been pushing for for a while. Because we've collected a bunch of free-form school names from two years of hackathons, we have a pretty good dataset that you can clean and add.

**Comment by lengstrom** [comment]
A great tool for this is: https://github.com/leereilly/swot !
ᐧ

**Comment by xTEddie** [comment]
Yes, I used  https://github.com/leereilly/swot to gather the Canadian and US schools and added some changes on it.

Here's the list:
[schoollist.txt](https://github.com/techx/quill/files/900542/schoollist.txt)

**Comment by jlin816** [comment]
Done in #43.
