### ISSUE TITLE
Auto-populate team list upon joining a team

### ISSUE THREAD

**Issue by turbomaze** [techx/quill#20]
* currently, when you join a team that contains other people, you do no see any of their names
* this confuses users and makes them think they messed up
* upon page refresh, everything is made clear
* the data should be loaded dynamically upon joining a team so that no refresh is needed
* note: we've fixed this problem already on some branch of the hackmit version of quill, and it was a simple fix

**Comment by ehzhang** [comment]
Anyone want to submit a quick PR?

https://github.com/techx/quill/blob/master/app/client/views/team/teamCtrl.js#L34
