### ISSUE TITLE
Resume upload?

### ISSUE THREAD

**Issue by jacobsokora** [techx/quill#23]
Is there anything special to be done for this or should it just be a link to a dropbox users can upload to? It's not very clear due to lack of documentation and the default link just redirects to an inactive dropbox.

**Comment by jlin816** [comment]
Hey Jacob! There's nothing special to be done here. We've just linked to a Dropbox in the past, and it's been fine for our purposes. If you guys implement a better solution for resume upload, feel free to put in a PR!

**Comment by jacobsokora** [comment]
Thanks so much, that's what I thought just wanted to make sure

**Comment by ravirahman** [comment]
The makemit version has direct upload to s3. I’m swamped rn but can submit a pull request later.

Ravi
