### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by lawja** [techx/quill#24]
So I have the server running, technically, but whenever I run it all the js plugins are being replaced with index.html, making the js console look like 
![screen shot 2017-06-19 at 7 40 16 pm](https://user-images.githubusercontent.com/9260091/27310308-5a1a73b2-5527-11e7-952a-c2961273c3da.png)
So I know this is because the src attribute is being pointed to the wrong location but I didn't move anything since cloning the repo and I can't really figure it out.

Any help would be appreciated.

**Comment by ehzhang** [comment]
Have you installed the necessary dependencies?

**Comment by ravirahman** [comment]
Yes...these are signs of 4xx errors. Check the network tab to see why they
aren't loading (could be not found; could be a mime type, etc...)

**Comment by lawja** [comment]
Yep all dependencies installed. And these are all 304 status codes on the files, just getting thrown syntax errors because the js file are being replaced with index.html

**Comment by ravirahman** [comment]
Ah…something with routing isn’t working. Use some debug statements to figure out where the error is. Also check to make sure the hostname and port are correct.

Ravi

**Comment by ehzhang** [comment]
It's likely the case that the files can't be found, and are thus being caught with [the wildcard](https://github.com/techx/quill/blob/master/app/server/routes.js#L11).

I did a fresh setup and didn't run into any issues.

How did you install the dependencies, and are you running the app with `gulp server`?

**Comment by patins** [comment]
Sounds like it needs `bower install`

**Comment by lawja** [comment]
Yeah that was it, I apologize for my incompetence lol, thanks!
