### ISSUE TITLE
Add SSL Options to Environment

### ISSUE THREAD

**Issue by at0dd** [techx/quill#29]
As an added feature, add easy to setup SSL that's compatible with [LetsEncrypt](https://letsencrypt.org/).

Would require two variables in the .env, and a modification to app.js where if the certificate was specified, read the file and start a server. If no certificate is specified the app will listen as normal.

**Comment by at0dd** [comment]
Also, thoughts on forcing https?

**Comment by ravirahman** [comment]
From a devops perspective, it's easier to enforce https at the load
balancer, and then run the app on a very high port unencrypted. If you run
on 443, you will need to run as root.

**Comment by at0dd** [comment]
Good point! I ended up just forcing through nginx with a proxy pass. I'll go ahead and close this issue and #30
