### ISSUE TITLE
Team name error

### ISSUE THREAD

**Issue by gauthamzz** [techx/quill#69]
A couple of particpants when trying to use team name : `TEAM #007` the team name was not shown in others.  

![28313137_2081414695422686_1228698588_n](https://user-images.githubusercontent.com/12110844/36590412-9a2ff412-18b4-11e8-918c-7a07e6a30844.jpg)
![28449840_2081414608756028_2077116892_n](https://user-images.githubusercontent.com/12110844/36590414-9a681b4e-18b4-11e8-9e16-3f2ea55121e0.jpg)

Upon using admin, i was able to find only one persons name with team #007.

**Comment by at0dd** [comment]
Can you elaborate on "the team name was not shown in others."? Is the list of team members not showing up for the members?

**Comment by gauthamzz** [comment]
Four people registered with same team name but in the search only one person was shown.  Other memebers were not shown.  it’s werid 😅

**Comment by at0dd** [comment]
Hmm I just tested this locally and it worked, and from your screenshots it looks like the names are explicitly the same (team names are case sensitive). Are you able to browse the database for these users and verify that the `teamCode:` is `TEAM #007`?

**Comment by jlin816** [comment]
Closing for now, please re-open another issue if you still have any problems!
