### ISSUE TITLE
500 when trying to save application form

### ISSUE THREAD

**Issue by lgg** [techx/quill#72]
Everything works fine
Changed graduation years in 
```
client/views/application/
server/models/User.js
and views and stats
```

run
`gulp server`

Now can't save application form

`PUT /api/users/SOMETOKENHERE/profile 500 171.183 ms - 66`

I checked #1 but it seems that function https://github.com/techx/quill/issues/1#issuecomment-248448059 is already updated

**Comment by jlin816** [comment]
What is the error output?

**Comment by lgg** [comment]
@jlin816 on server side in console: 
```
PUT /api/users/SOMETOKENHERE/profile 500 171.183 ms - 66
```

On client side: `Oops, something went wrong`

**Comment by lgg** [comment]
Tried to reinstall npm modules - didn't help.
I have made some localization for text, so on client side:
![image](https://user-images.githubusercontent.com/12018713/37317711-8813a082-2677-11e8-8838-f318c0707215.png)

On server side:
![image](https://user-images.githubusercontent.com/12018713/37317735-a37523c8-2677-11e8-920d-34651dc17b47.png)

**Comment by lgg** [comment]
Hmm, i even don't understand how i can debug it :/

**Comment by lgg** [comment]
Such user contains in MongoDB
![image](https://user-images.githubusercontent.com/12018713/37318801-75aebfde-267d-11e8-89fa-1653c1a1f27c.png)

**Comment by lgg** [comment]
Shame on me :/

For others: check MongoDB schema and Users model.

I have this code in User.js:
```
schema.statics.validateProfile = function(profile, cb){
  return cb(!(
    profile.name.length > 0 &&
    profile.adult &&
    profile.school.length > 0 &&
    ['2018 2019 2020 2021 2022 2023 2024 2025'].indexOf(profile.graduationYear) > -1 &&
    ['M', 'F', 'O', 'N'].indexOf(profile.gender) > -1
    ));
};
```
But correct one is:
```
schema.statics.validateProfile = function(profile, cb){
  return cb(!(
    profile.name.length > 0 &&
    profile.adult &&
    profile.school.length > 0 &&
    ['2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'].indexOf(profile.graduationYear) > -1 &&
    ['M', 'F', 'O', 'N'].indexOf(profile.gender) > -1
    ));
};
```
