### ISSUE TITLE
Is it possible to use custom fields in the application page?

### ISSUE THREAD

**Issue by vgiotsas** [techx/quill#75]
Is it possible to use the custom questions instead of the default (e.g. I want to omit the graduation year)?
I couldn't find it in the Admin panel or the existing documentation, any pointers will be very helpful.

**Comment by jlin816** [comment]
If you want to edit the application questions, you can change the files indicated here: https://github.com/techx/quill#application-questions

**Comment by jlin816** [comment]
Closing for now -- open another issue if you still have any problems!
