### ISSUE TITLE
Postinstall script error

### ISSUE THREAD

**Issue by taricjain** [techx/quill#89]
this probably is a stupid mistake we made, but could someone shed some light on this error?
<img width="728" alt="error" src="https://user-images.githubusercontent.com/17219764/44795162-ac958600-ab6f-11e8-957c-41473cc255aa.png">

i tried rebuilding gulp-sass which did help and updated gulp, but this still shows up. Has anyone else faced this? 

Note: we were able to work this a month or two ago, but the dev team went away for the summer and now these issues are popping up out of nowhere.

@kirandasika98

**Comment by jlin816** [comment]
What version of gulp are you using?

**Comment by taricjain** [comment]
CLI version - 2.0.1
Local - 3.9.1

**Comment by taricjain** [comment]
So here's the thing, if I run the app (node app.js) it works. But I don't know why using "gulp server" (gulp watch) doesn't work. I have not worked with gulp before, so I do not know what's wrong, but I was just trying to follow the README which asked to start the mongo connection and run "gulp server." Could you explain what is happening?

**Comment by jackcook** [comment]
I'm going to close this issue because we've moved past bower at this point, but let me know if you have any other issues with Quill!
