### ISSUE TITLE
Porting Backend to Laravel (PHP)

### ISSUE THREAD

**Issue by SalahEddineBC** [techx/quill#96]
Hello, 
we are intressted to deploy this platform for our hackathon but our server is limited to cpanel only, we dont have ssh access for the moment, we can only deploy PHP apps only, are there any plans to port it to any PHP framework ?
thanks

**Comment by jlin816** [comment]
Unfortunately, we don't have plans to port it to PHP at the moment! We haven't seen much demand / interest in this.

**Comment by SalahEddineBC** [comment]
our team are discussing about the possibility to rewrite the backend with laravel framework
thanks for the reply
